services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: gpt_checker
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ASSISTANT_ID=${OPENAI_ASSISTANT_ID}
      - REDIS_PORT=6379
      - PORT=3000
    ports:
      - "3021:3000"
    volumes:
      - ./uploads:/usr/src/app/uploads

volumes:
  redis-data:
